name: deep-learning-20
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pytorch=1.6.0
  - torchvision=0.7
  - cudatoolkit=10.2
  - cudnn=7.6.5
  - tensorboard
  - jupyter
  - jupyterlab
  - nb_conda
  - matplotlib
  - scipy=1.5.2
  - scikit-learn
  - Pillow
  - nltk=3.5
